### ISSUE TITLE
Add coala README

### ISSUE THREAD

**Issue by sims1253** [LappleApple/feedmereadmes#1]
I'd like to add the coala README to this :)
https://github.com/coala/coala/blob/master/README.rst

**Comment by LappleApple** [comment]
Hey @sims1253, thanks for submitting this. I've made a tweet to spread the word — you might share it: https://twitter.com/LauritaApplez/status/831801232863932416.

**Comment by LappleApple** [comment]
Just sent you a PR for this. :)
