### ISSUE TITLE
criu

### ISSUE THREAD

**Issue by xemul** [LappleApple/feedmereadmes#11]
Hello,

It would be nice to get your feedback on https://github.com/xemul/criu

Thanks!
-- Pavel

**Comment by LappleApple** [comment]
@xemul Thank you for the submission. Will get to it ASAP.

**Comment by LappleApple** [comment]
Hi @xemul, here are some suggestions!
- I'm going to assume that a lot of the essentials (mostly identified in this README template: https://github.com/zalando/zalando-howto-open-source/blob/master/READMEtemplate.md )are covered in the CRIU website content. In that case, I'd use the README to point people to specific sections of the CRIU website that they're going to want to access quickly—ie how to download/install/run/configure instructions, technical requirements, common troubleshooting needs, a docs section for developers/potential contributors, and a project roadmap (if you have one). 
- You can use [this product template](https://github.com/zalando/zalando-howto-open-source/blob/master/producttemplate.md) or some similar one to draft a few sentences explaining more about the project's purpose and usefulness. Some things I'd like to see:
- Why did you make this?
- Is it like anything else out there? If not, state that. If yes, then how's it different?
- Who's using this (your docs cover this question in the line, "CRIU started as a project of Virtuozzo and grew with tremendous help from the community. It is currently used by (integrated into) OpenVZ, LXC/LXD, Docker, and other software, and CRIU packages is included into many Linux distributions. ")
- do you have any user testimonials to suggest that the project has helped them work better/smarter/more effectively/faster/with less friction?
- What's its development status? Do you want contributors, and if so, what do you want them to work on--your bugs? 
- If I'm a newbie who wants to work on this project, how can I get started? You have a lot of open issues so perhaps label some as "for first-time contributors" or "no coding needed" to grow your contributors community.
- Use full title in the tagline: "A project to implement checkpoint/restore functionality for Linux"
- Add more relevant tags (Linux, for example) to increase search relevance.

Hope this helps! Come back if you'd like a closer README review. :)
