### ISSUE TITLE
Requests for Main/Writers for Webpack

### ISSUE THREAD

**Issue by TheLarkInn** [LappleApple/feedmereadmes#13]
Hello Lauri!!! Our open source e project webpack has an extensive need for those who would like to help us review or write for our documentation page!! 

Here is the issue you mentioned I should add to this issue tracker!!! https://github.com/webpack/webpack.js.org/issues/1380

**Comment by LappleApple** [comment]
@TheLarkInn Thanks, Sean! Hoping we find you some help ASAP.

**Comment by fokusferit** [comment]
@TheLarkInn I would like to help you guys with webpack and documenting parts, reviewing it. I'll also try to get one or two other developers :) 

Will check out your Issues list.

**Comment by fokusferit** [comment]
@TheLarkInn @LappleApple we had a cool first hangout with Even regarding webpack-cli and we hope to help them webpack-cli team more regarding documentation but also coding 😄

**Comment by LappleApple** [comment]
Great to hear!

**Comment by LappleApple** [comment]
Hi! Any new developments here? Wondering how things are going.

**Comment by TheLarkInn** [comment]
Hi there!!! Sorry just finished a cross-country travel trip so I've been away the past few days. Now that I'm getting settled in I'm happy to follow up and help facilitate anything needed. Thanks for the ping @LappleApple

**Comment by fokusferit** [comment]
We started a first discussion with some people at Zalando and our current first step is to get more clarity about the project, updating documentation, defining a roadmap for us to work on etc.

I've started a conversation at two issues https://github.com/webpack/webpack-cli/issues/181, https://github.com/webpack/webpack-cli/issues/180 so feel free to give us feedback @TheLarkInn .

I've also started on a PR regarding some issues (updating Readme) and hopefully this week, there will be a PR people can work on, give feedback

**Comment by LappleApple** [comment]
Hi, I'm closing out this issue as it seems conversation can take place separately/between you.
