### ISSUE TITLE
Chemfiles readme

### ISSUE THREAD

**Issue by Luthaf** [LappleApple/feedmereadmes#14]
Hi !

Thank you very much for proposing this, it will be very useful to the whole open-source world.

Could you give a look at the readme of the chemfiles library: https://github.com/chemfiles/chemfiles?

The project intended audience is scientists who are not necessary developers, put are putting together small scripts/programs for research. I'm not telling more, I hope the README can explain the rest =)

Thank you very much !

**Comment by LappleApple** [comment]
Thanks, @Luthaf! Will look at it ASAP.

**Comment by LappleApple** [comment]
Hi @Luthaf, just edited your README: https://github.com/chemfiles/chemfiles/pull/88

Thanks for submitting!
