### ISSUE TITLE
Add page for README/docs inspiration

### ISSUE THREAD

**Issue by LappleApple** [LappleApple/feedmereadmes#16]
With links:
- http://www.ybrikman.com/writing/2014/05/05/you-are-what-you-document/
- https://www.hanselman.com/blog/BringKindnessBackToOpenSource.aspx
- How to Write Documentation for People that Don't Read: https://www.youtube.com/watch?v=sQP_hUNCrcE
- http://hilton.org.uk/presentations/documentation
- http://codewerdz.org/
- https://insights.hpe.com/articles/how-to-write-documentation-thats-actually-useful-1707.html
- http://codewerdz.org/
- http://blog.izs.me/post/161633971373/documentation-driven-development
- Andrea Goulet: Communication is Just as Important as Code: https://www.youtube.com/watch?v=VFuNdKPV0jc&feature=youtu.be
- https://www.youtube.com/watch?v=sQP_hUNCrcE
- Slides: kev.inburke.com/slides/documentation

**Comment by LappleApple** [comment]
Done.

**Comment by janpio** [comment]
If anyone is looking for the result as I did: 
https://github.com/LappleApple/feedmereadmes/blob/master/Inspiration.md

Looking good!
