### ISSUE TITLE
iText 7 readme review

### ISSUE THREAD

**Issue by amedee** [LappleApple/feedmereadmes#17]
Feel free to have a go at the `README.md` (and other `.md` files) of iText:

https://github.com/itext/itext7

Some of the files have a very long history, which isn't reflected by the Git history, because they used to be `.txt` files. Also, we used SVN in prehistoric times, see https://sourceforge.net/p/itext/code/HEAD/tree/trunk/itext/ (scheduled to be deleted)

**Comment by LappleApple** [comment]
Thank you, @amedee. Will take a look ASAP!

**Comment by LappleApple** [comment]
I'll close this for now as it's been a while since hearing back.
