### ISSUE TITLE
Diesel review

### ISSUE THREAD

**Issue by sgrif** [LappleApple/feedmereadmes#20]
Hey folks,

Thanks in advance for taking the time to look at this. I'm interested in feedback for [Diesel's README](https://github.com/diesel-rs/diesel). We also have a lot of stuff on our website [diesel.rs](https://diesel.rs), so the README Is intentionally a bit light. (Not sure if y'all are interested in reviewing websites as well)

**Comment by LappleApple** [comment]
Thanks for the submission. Will get to it ASAP. :)
