### ISSUE TITLE
Cockatrice review request

### ISSUE THREAD

**Issue by Daenyth** [LappleApple/feedmereadmes#21]
I'd appreciate a review on cockatrice: https://github.com/cockatrice/cockatrice/

**Comment by LappleApple** [comment]
Thanks for the submission, @Daenyth. Will get to this ASAP!

**Comment by TaylorShiells** [comment]
Hello @LappleApple and @Daenyth , I'm a technical writer whose new to GitHub and I'm hoping to do some work for FeedMeReadMes. I know a little about Cockatrice so I'd like to help here, do you have any advice on how to get started?

**Comment by Daenyth** [comment]
Well, I'd read over the readme - it's written for two audiences; developers and users. Primarily the developers, since most users should end up on the website instead of the github page. If you can give feedback for clarity and usefulness to those audiences I'd appreciate it

**Comment by LappleApple** [comment]
@TaylorShiells I'd check the project's contributor guidelines, then making an edit based on those. :)

**Comment by TaylorShiells** [comment]
I've taken a look at the project's readme and it's contributor guidelines and comparing them to the [FMRM Maturity Model](https://github.com/LappleApple/feedmereadmes/blob/master/README-maturity-model.md)

Here are a few observations I have:
1. The readme is currently lacking contributor guidelines and a style guide for the documentation itself. This is something that will encourage and direct further contributions.

2. There are things to fix about the spelling and grammar, but nothing that seriously affects readability. Still, it can be cleaned a bit once a style guide is in place.

3. Going off the maturity model, several areas are at stage 3 or 4 in the model, but a few other steps are missing. The first areas to expand are in metrics for completion (You have a good one for translation but more can be drawn from the roadmap) and in pull-request response times.

**Comment by LappleApple** [comment]
Great comments, @TaylorShiells. Following the Maturity Model isn't mandatory for projects submitting to FMRM, it's only advisory. But great that you've read the model and are applying it. :)

**Comment by TaylorShiells** [comment]
I made my first pull request, it's focused on establishing a style guide so there's a starting point for editors to hop on and work. I'll start communicating within the Cockatrice project itself from here out.

@LappleApple I would like to discuss that with you as something that should be in the Maturity Model, because I think there's a problem of writers/editors not knowing how to start.

**Comment by LappleApple** [comment]
@TaylorShiells Hi! So I'm clear, you're suggesting that the MM should have a style guide?
