### ISSUE TITLE
VaporShell Readme.md Review Request

### ISSUE THREAD

**Issue by scrthq** [LappleApple/feedmereadmes#22]
## First:

Thank you so much for offering this service! It's pretty fantastic!!

## Second - Here's the GitHub project Readme that I would love some help with:

https://github.com/scrthq/Vaporshell/blob/master/README.md

## Third - Background:

The Readme I have there is mainly a pointer towards the documentation site I build on top of GitHub Pages w/ a custom domain. I've been building VaporShell completely solo, down to the website design (http://vaporshell.io/), all of the source code, and any associated Readme's. It's the first project I've really done on this scale and is for a tool that I feel is a huge help to SysAdmin's working in AWS with CloudFormation / Infrastructure as Code in general. VaporShell itself is a PowerShell module designed to allow easy creation of CloudFormation templates by leveraging Powershell's featureset and syntax. This allows you to do things like tab-completion of valid values for specific parameters, tab completion of resource parameters in general (there are over 600 resource types available in CloudFormation with varying property sets between each one, so remembering all of those tends to be a little overwhelming), and many other things. Another key point for the project is cross-platform compatibility, now that PowerShell Core / .netcore is becoming a bigger focal point. All development and CI tests are done on both .NetFramework (Windows/AppVeyor) AND .NetCore (Ubuntu for local dev/testing, Ubuntu/macOS in Travis CI for CI integration)

## Fourth - Plans for the near future:

v2.0.0 is coming soon (within the next month). Updates are geared around including full CloudFormation stack management (i.e. deploy/update/delete/monitor -- current iteration is template building only) via the .NET / .netcore SDK's from AWS

Thanks again for helping out OSS projects!

- Nate / SCRT HQ

**Comment by LappleApple** [comment]
Hi there! I'm going to suggest you copy-paste from your set of docs the nuggets that would inform a brief README—using [this template](https://github.com/zalando/zalando-howto-open-source/blob/master/READMEtemplate.md) or a different one, like [this structured README template](https://github.com/shaloo/structuredreadme). Then I'd be happy to take a look at the file. :)

**Comment by scrthq** [comment]
Awesome! I'm on it and will reply back once updated!! I appreciate the quick feedback!

**Comment by scrthq** [comment]
Hiya, @LappleApple ! Just released v2.0.1 and made a ton of updates to the README! I think I'm ready now 💃

**Comment by scrthq** [comment]
@LappleApple thanks for the feedback and edits!!! Greatly appreciated!!!! Closing this out, you are awesome!
