### ISSUE TITLE
ffind review

### ISSUE THREAD

**Issue by jaimebuelta** [LappleApple/feedmereadmes#23]
Hey there!

I'm looking for feedback in the [ffind README](https://github.com/jaimebuelta/ffind) page. 

Thanks a lot in advance! This is a great initiative

Cheers,
  Jaime

**Comment by LappleApple** [comment]
Heya, a few quick things I'd do: 
- Make sure your install/build/test/run documentation is as thorough as possible--consider running through it with a friend who's using it for the first time, and note where they get stuck. Then fix.
- Shove all of that step-by-step into its own .md file and include the link in your readme, to let readers know it's there.
-  Add a "Troubleshooting" guide and link to *that* from your Readme--don't post it as a section there. :) 
- Definitely add a Contributing.md so contributors know what you're looking for and how to contribute. Like the "Troubleshooting Guide," add a referencing section to it from the Readme with the link to the dedicated .md file.
- No need to post the licensing section at the bottom -- you have the dedicated file there.

Hope this helps (after almost six years!). :)

**Comment by LappleApple** [comment]
Closing this issue as I provided a response. Feel free to reopen if necessary. :)
