### ISSUE TITLE
Explain the role of wikis, and use the wiki here

### ISSUE THREAD

**Issue by jhermann** [LappleApple/feedmereadmes#28]
Opening a project's wiki to any registered user can open a breeding ground / incubator for catching ideas in raw form and polishing them for inclusion into the "official" documentation. It fosters collaboration much more so than the rigid time-line format of an issue thread, and potentially lowers the threshold for new contributors.

Like in this project, where you could have a page to discuss improvements of the "Inspiration" page. :wink: 

A README should link to the wiki, and explain what it's main purpose is (main docs, experiments / drafts, …).

**Comment by LappleApple** [comment]
Hi @jhermann I'm not sure I follow. Are you proposing ideas for this project, or proposing text to include in this README? FWIW I'm not currently planning on making this project super-ambitious (keeping it simple to the exchange of editing help), so a wiki would be outside of scope for now.

**Comment by jhermann** [comment]
Both. A README sits centrally in an ecosystem of docs, with the code + tests, the "main" docs, and a wiki being related parts of the overall documentation, each filling a specific role.

A README in isolation really only works for simple and small projects.

**Comment by LappleApple** [comment]
Well, as the README of this project notes, I don't have capacity at the moment to take on documentation sets or wikis. So I think I'm good for now. Thanks!
