### ISSUE TITLE
Radera Victory

### ISSUE THREAD

**Issue by deni** [LappleApple/feedmereadmes#29]
Hey! I hope that I'm doing this right. We're not really free (beer), but I hope to get some help anyway. Saw Stephanie retweet it — awesome initiative.

https://github.com/radera/victory/blob/master/README.md

**Comment by LappleApple** [comment]
Thanks for the submission, @DSDeniso. Just tagged it for others to claim, or I'll get to it ASAP. :)

**Comment by ItsPugle** [comment]
I feel as though the Installation part of Getting Started needs some more comments. Little observation :)

**Comment by LappleApple** [comment]
@ItsPugle Thanks! Do you have specific requests or suggestions that could help prevent potential users from getting stuck?

**Comment by ItsPugle** [comment]
Maybe it's worth expanding on what each command does?

**Comment by cmariebeau** [comment]
Hi guys, I have a couple edits as well. I'll submit a PR. :-)

**Comment by cmariebeau** [comment]
Hi there, I submitted a pull request last week. Let me know if you have any questions.

**Comment by LappleApple** [comment]
That's great, @cmariebeau :)
