### ISSUE TITLE
Feedback on README for Solidarity

### ISSUE THREAD

**Issue by GantMan** [LappleApple/feedmereadmes#30]
I've been doing READMEs for a long time, and the one thing I've learned is that it can **ALWAYS** get better.  I'm happy to hear and incorporate awesome feedback on my readme doc.

The project is planned to be officially released in about a week.
https://github.com/infinitered/solidarity

**Comment by LappleApple** [comment]
Thanks, @GantMan -- I like your attitude. :) Just tagged it for someone else to claim, or I might get to it ASAP.

**Comment by ddncn** [comment]
Just took a quick read of the README and spotted a few (simple) things I could suggest. I’ll write it up and toss a PR your way. No guarantees I’ll catch everything though. :)

**Comment by GantMan** [comment]
Thanks so much!  Love the changes!  Happy to get feedback from more, or feel free to close if you think we're 💯

**Comment by LappleApple** [comment]
@ddncn Thank you for this contribution! @GantMan, should we close this issue out now?

**Comment by GantMan** [comment]
Happily!  Thanks for such a remarkable service to the community!
