### ISSUE TITLE
Results?

### ISSUE THREAD

**Issue by janpio** [LappleApple/feedmereadmes#34]
Super interesting project.

I was hoping to see the before/after of some reviews somewhere, maybe links to issues or PRs created. Or to say it in the words of the maturity model:

> [...] evidence of past performance in real development situations.

😄 

Did I miss it or doesn't this exist (yet)?

**Comment by janpio** [comment]
Found a linked PR in one of the issues: https://github.com/LappleApple/feedmereadmes/issues/10#issuecomment-315100479 Some others mention PRs, but no links.

**Comment by LappleApple** [comment]
A lot of times the reviews amount to comments/questions. But this is a good idea for standard edits.
