### ISSUE TITLE
Feedback on the code_gym a computer science study space

### ISSUE THREAD

**Issue by williscool** [LappleApple/feedmereadmes#37]
Figured why not ask.

Description

```
I have written, tested, documented, and linted several hundred data structures, algorithms, and coding problems in javascript.
```

https://github.com/williscool/code_gym/blob/es6ify/README.md

https://github.com/williscool/code_gym/blob/es6ify/javascript/js_README.md

**Comment by LappleApple** [comment]
Thanks for the submission--will get to this ASAP if nobody else does. :)

**Comment by LappleApple** [comment]
Heya, have a look at this template and see if it would work for your project:
https://github.com/dec0dOS/amazing-github-template#readme

You'll find there a list of .md files that are quite helpful for driving contributions, if that's one of your aims. If it's not one of your goals, then I'd recommend creating a structure with bullet points highlighting what users will learn and find in your repos and then including the links to take them directly there. You have some of this in place already in the js_readme.md so I'd build that out. Also I'd highlight in the first section of your Readme the "objectives for the user" -- ie what are the top 3-4 benefits for your users? What knowledge will they gain, or what will they be able to do, that they couldn't do before checking out your work?

**Comment by LappleApple** [comment]
Closing this issue as I provided a response. Feel free to reopen if necessary. :)
