### ISSUE TITLE
Sprig Template Function Library

### ISSUE THREAD

**Issue by technosophos** [LappleApple/feedmereadmes#4]
I was so excited to see your project! What a fabulous idea. I would be interested in some feedback on the Sprig project's README.

https://github.com/Masterminds/sprig/blob/master/README.md

Thank you!

**Comment by LappleApple** [comment]
Thanks, @technosophos. I have one project in line before this one, but will get to it ASAP. cc @Ingmar84

**Comment by jvallera** [comment]
Great! Here is the project on Pulse: https://www.mozillapulse.org/entry/339
Thanks!

**Comment by LappleApple** [comment]
Thank you so much for your efforts, @jvallera. :)

**Comment by LappleApple** [comment]
Hey @technosophos, took a look and pulled a request :)

**Comment by technosophos** [comment]
Thanks!
