### ISSUE TITLE
Please review the README for kerl

### ISSUE THREAD

**Issue by jadeallenx** [LappleApple/feedmereadmes#40]
Thank you for this project!

Our project helps people manage and install different versions of Erlang. I know our [README](https://github.com/kerl/kerl/blob/master/README.md) could use some editing and review.

**Comment by LappleApple** [comment]
Thanks for the submission--will get to this ASAP if nobody else does. :)

**Comment by LappleApple** [comment]
Sometimes ASAP is ... a while. But better late than never, I hope!

First impression is that this Readme is too long. Guidance below will help you shorten it and organize your docs.

I’m big on Tables of Content so would recommend adding one at the top.

Add a section at the very top, but below the ToC, answering for prospective users and contributors: "Why Kerl?" Then answer in that section:
- Is this project like any other? If so, what distinguishes it from the rest?
- What are its primary features and why? 
- I’d move up the “How It Works” section and then make sure it’s A) brief B) covers very basic themes, which you can elaborate upon elsewhere in the repo as separate .md files.

I like that you highlight your triage cadence and IRC info. I’d collapse those two sections and make a “Contributing and Support” section — or if you wish to elaborate on those topics further, create one for each. Regarding support: do you try to get back to people within a set time period — 24-48 hours? A week? I’d add that to set expectations. 

I’d move all download/install/build/test/run/use info to its own .md file to declutter the Readme, then link to it from the Readme. Do you currently set up this info in chronological order, to reflect what a first-time user would go through to get up and running? It looks that way. I’d make sure that these steps are failsafe — try running through them with a first-timer, notice where they get confused or stuck, then adapt your docs to resolve those issues.

Would create a separate file for config details and link to it from the Readme. 

Would pull out the Glossary section and store it in a dedicated .md. 

Ditto for the commands reference. 

Create a separate changelog.md, then link to it from the readme. 

Add a Troubleshooting guide highlighting common issues and link to it from the Readme.

Some files I’d add to your repo:
- Governance.md noting different contributor types (contributor, maintainer, user) and describing your processes for making decisions.
- maintainers.md listing maintainers.
- contributing.md describing how you want people to contribute. Once you have this, link to it from the Readme.
- Code of conduct.md 
- Dedicated license.md so it’s very noticeable (looks like you’re using MIT)?
- Roadmap.md describing future plans for the project, which helps to attract contributors.
- security.md to help you promptly handle critical issues and give users/contributors a way of reporting such issues.
- Adopters.md listing users and how they've used the project.

Hope this helps!

**Comment by LappleApple** [comment]
Closing this issue as I provided a response. Feel free to reopen if necessary. :)
