### ISSUE TITLE
Italian Digital Citizenship APIs README

### ISSUE THREAD

**Issue by cloudify** [LappleApple/feedmereadmes#43]
Hi @LappleApple ,

one of the projects of the Italian [Digital Transformation Team](https://teamdigitale.governo.it/en/) is to build a set of API that will be used by government agencies as the foundation for their digital services.

We're currently working on the first iteration of these APIs that will provide:

* a communication interface for sending messages to citizens through several digital channels (initially e-mail and SMS)
* a repository of user preferences that citizens can set and that services can read to deliver personalized experiences to the citizens

This is the [main repository of the APIs code](https://github.com/teamdigitale/digital-citizenship-functions), with the README (the audience is toward contributors and service developers).

Thanks in advance for the feedback! ❤️

**Comment by LappleApple** [comment]
Hi -- I took a quick look and suggest making a dedicated docs page for this information, then keeping the README lightweight by using this template (https://github.com/zalando/zalando-howto-open-source/blob/master/READMEtemplate.md) or a similar one to cover high-level, basic info.

**Comment by LappleApple** [comment]
Heya, closing this as the project's now archived.
