### ISSUE TITLE
Feedback on WordPress Plugin Boilerplate Powered Readme

### ISSUE THREAD

**Issue by Mte90** [LappleApple/feedmereadmes#44]
This is my project that is used from different people but I am not sure how much is easy to understand the readme.
https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered

**Comment by LappleApple** [comment]
Hi @Mte90: Thanks for your submission. I'm going to suggest that you check out this template (https://github.com/zalando/zalando-howto-open-source/blob/master/READMEtemplate.md) and others shared in this project repo and restructure your README to follow it/the template you find most useful. Then ping back to say "I'm ready." How does that sound?

**Comment by Mte90** [comment]
I made few improvements following that doc, but I hope to recheck again ASAP.

**Comment by Mte90** [comment]
Improved more the readme, done :-)
It is funny that I was already using many of the hints suggested, I am not after all a dev without experience in interesting Readme 😂
