### ISSUE TITLE
Please review this readme on resources for front-line engineering managers

### ISSUE THREAD

**Issue by VGraupera** [LappleApple/feedmereadmes#46]
Would really welcome your advice on this readme! Thanks.

https://github.com/VGraupera/manager-resources

**Comment by LappleApple** [comment]
Hi @VGraupera, I took a look and it all looks good to me -- sometimes with resources like this it's better to stick to the info like you've done, vs. write a lot of introductory text. 

You might want to keep your project independent, but you might also consider merging with this other project I've got: https://github.com/LappleApple/awesome-leading-and-managing. I can also reference your list there. Let me know which option you prefer.

**Comment by LappleApple** [comment]
Closing this issue as I provided a response. Feel free to reopen if necessary. :)
