### ISSUE TITLE
React State Management Blog Post

### ISSUE THREAD

**Issue by GantMan** [LappleApple/feedmereadmes#48]
Finishing up a blog post to go with this repo, I'd love to have some feedback:

https://github.com/GantMan/ReactStateMuseum

I will link to the blog post when it is published, of course!

**Comment by LappleApple** [comment]
Heya, a few ideas for you:
- I'd start the Readme with a very clear, concise "what this is, and why it exists/what problems it solves" section. What inspired you to create it? How are you using it? How are others using it? This would be interesting.
- I'd either move the "One Packing List App Written in:" section to its own .md and link to it from the Readme, or move it below the "what this is and why" section.
- I'd move the Contributors table to its own .md file with a link from the Readme
- You don't seem to have a Contributing.md -- are you actively looking for more contributors? If so, I'd add this file and describe how you want people to contribute (here's a good example: https://velero.io/docs/main/start-contributing/)
- I'd add a maintainers file so people know who is accountable for the project
- would add a changelog.md, a roadmap.md, a code of conduct.md, and adopters.md if you'd like to highlight who's using your project and how. This can inspire others to use it, too.

Hope this is helpful!

**Comment by GantMan** [comment]
thanks so much for this!
