### ISSUE TITLE
Gaphas README

### ISSUE THREAD

**Issue by danyeaw** [LappleApple/feedmereadmes#54]
Hi, I just spent a lot of effort completely revamping the README for [Gaphas](https://github.com/gaphor/gaphas). I would very much appreciate some feedback to help me further sharpen the why, how, and what, and of course any other feedback would be awesome as well. :heart:

**Comment by janettech** [comment]
Hi @danyeaw, are you still looking for help on the README? I would be interested to look at it. 
Thanks!

**Comment by danyeaw** [comment]
@janettech I would ♥️ to have both the [Gaphas](https://github.com/gaphor/gaphas) and [Gaphor](https://github.com/gaphor/gaphor) READMEs reviewed, I really appreciate any feedback!

**Comment by janettech** [comment]
I will. Thanks!

**Comment by danyeaw** [comment]
Closed by https://github.com/gaphor/gaphas/pull/48. Thanks @janettech!
