### ISSUE TITLE
Gaphor README

### ISSUE THREAD

**Issue by danyeaw** [LappleApple/feedmereadmes#55]
Hi, I just spent a lot of effort completely revamping the README for [Gaphor](https://github.com/gaphor/gaphor). I would very much appreciate some feedback to help me further sharpen the why, how, and what, and of course any other feedback would be awesome as well. :heart:

**Comment by shweta345** [comment]
Hi Dany, Would you be interested in collaborating to create documentation for your software? If yes, please feel free to email me at shweta.shetye@gmail.com.

I am an experienced technical writer and have created documentation for multiple domains. I am new to open source documentation, but keen on getting started. I can help you create a wiki or a standalone website with how-to tutorials that can help you explain the product a tad better than your readme :)

**Comment by yugoPanorama** [comment]
Hi @danyeaw !  Are you still looking for feedback on your README?

**Comment by danyeaw** [comment]
@yugoPanorama Yes, we would love some help!

**Comment by danyeaw** [comment]
We are still looking for some help reviewing our README 😄
