### ISSUE TITLE
Marble Marcher: Community Edition README review

### ISSUE THREAD

**Issue by WAUthethird** [LappleApple/feedmereadmes#56]
Hi! I manage the project for the community edition of a game, the upstream of which has stopped development. I'm a bit worried about the size of the README itself, even though the building process itself is quite complex and warrants the size. If you have any suggestions, it'd be much appreciated. Thanks!

[Link](https://github.com/WAUthethird/Marble-Marcher-Community-Edition/blob/master/README.md)

**Comment by yugoPanorama** [comment]
Hi @WAUthethird !  Are you still looking for feedback on your README?

**Comment by WAUthethird** [comment]
Yes @yugoPanorama! That'd be great.
