### ISSUE TITLE
Review README for Ubiety.Dns.Core

### ISSUE THREAD

**Issue by coder2000** [LappleApple/feedmereadmes#58]
Thank you for the work you guys do to help the community make everything better. I would like some assistance with the README I have for one of my projects. Please take a look at https://github.com/ubiety/Ubiety.Dns.Core#readme

**Comment by rimutaka** [comment]
https://dns.ubiety.ca is dead.

It's not clear what your library does. It's not even clear if it is a library or an app. The docs are just placeholders.

Contributing section seems to be a copy-paste from a template. It doesn't make much sense.

Drop "You can also use your favorite NuGet client.". Anyone with a favourite Nuget client already knows that.

Clone the repository and then restore the dependencies.
* Supported IDEs: Rider, VS Code or VS 2017
* .NET Core support: full

Drop "Building is simple"
What's in `build.ps1`? Any special steps the user needs to know about?

Links - seems to be redundant.
1. Everyone knows how to navigate Github and where to find issues.
2. Related projects - what do they do? The links don't tell me anyhting.

Maybe change 
> A reusable DNS resolver for .NET Standard 2.0
to
#### A reusable DNS resolver for .NET Standard 2.0

Thank you FOR the initial work TO
And I would move that to the end.
Are they Gihub users? Link to their profiles?

---

@coder2000 , was it helpful?
If yes, I would like a favour in return.
Tell me what you think of https://feedback.farm
I'm trying to validate the idea.

**Comment by LappleApple** [comment]
Heya @rimutaka, thanks a lot for jumping in here and sharing feedback. @coder2000, thanks for posting the initial request. I'm going to close this comment due to age and recommend to @coder2000 that if you'd like to continue the conversation with @rimutaka, that you open up an issue in your project repo. Good luck with your docs!
