### ISSUE TITLE
trashy

### ISSUE THREAD

**Issue by notklaatu** [LappleApple/feedmereadmes#8]
Saw your article on opensource.com

It's not on Github, but Gitlab accepts Github logins:
https://gitlab.com/trashy/trashy

**Comment by LappleApple** [comment]
Thanks!

**Comment by LappleApple** [comment]
@notklaatu Well, I've tried to edit your README but keep getting a 500 error from GitLab ... any suggestions?

**Comment by LappleApple** [comment]
Hi; I'll close this issue as it's been a while since my last note.
